version: "3"
services:
  sync:
    image: wazoplatform/wait
    environment:
      TIMEOUT: "${INTEGRATION_TEST_TIMEOUT}"

  plugind:
    image: "wazo-plugind-test"
    environment:
      - XIVO_UUID=cd030e68-ace9-4ad4-bc4e-13c8dec67898
      - WAZO_VERSION=17.10
    volumes:
      - "../..:/usr/src/wazo-plugind"
      - "./etc/wazo-plugind/conf.d/50-default.yml:/etc/wazo-plugind/conf.d/50-default.yml"
      # - "${LOCAL_GIT_REPOS}/wazo-bus/wazo_bus:/opt/venv/lib/python3.9/site-packages/wazo_bus"
      # - "${LOCAL_GIT_REPOS}/xivo-lib-python/xivo:/opt/venv/lib/python3.9/site-packages/xivo"
      # - "${LOCAL_GIT_REPOS}/wazo-market-client/wazo_market_client:/opt/venv/lib/python3.9/site-packages/wazo_market_client"
    ports:
      - "9503"

  market:
    image: "python:3.9-slim-bullseye"
    ports:
      - "8000"
    command: ["bash", "-c", "cd /var/www && python -m http.server"]

  rabbitmq:
    image: "rabbitmq"
    ports:
      - 5672

  auth:
    image: "wazoplatform/wazo-auth-mock"
    ports:
      - "9497"
